In [2]:
import numpy as np
import cv2
import glob
import matplotlib.pyplot as plt
import perception_lib as plib

# Step 1: camera calibration

In [16]:
randoImg = cv2.imread('rs/left/left-0000.png')
h,  w = randoImg.shape[:2]

## Left

Get the obj and img points.

In [25]:
Y = 9
X = 6

images = glob.glob('rs/left/*.png')
assert images
#print(images)

objpoints, imgpointsL = plib.FindAllChessCorners(X, Y, images)

In [26]:
print(np.asarray(objpoints).shape)
print(np.asarray(imgpointsL).shape)

(76, 54, 3)
(76, 54, 1, 2)


In [34]:
calLeft = cv2.calibrateCamera(objpoints, imgpointsL, (w, h), None, None) #ret, mtx, dist, rvecs, tvecs

In [40]:
print(len(calLeft[4]))
print(calLeft)

76
(0.3041656054358543, array([[374.15541243,   0.        , 322.54590143],
       [  0.        , 374.76827229, 245.03655092],
       [  0.        ,   0.        ,   1.        ]]), array([[-0.00355685, -0.00809662,  0.00356797,  0.00232191,  0.00040122]]), [array([[ 0.43028512],
       [-0.05311718],
       [ 2.54162613]]), array([[0.18736727],
       [0.02960226],
       [2.73118191]]), array([[ 0.04622488],
       [-0.05370393],
       [-3.11964087]]), array([[-0.15043358],
       [-0.00426849],
       [ 3.05671799]]), array([[-0.20206284],
       [ 0.08476387],
       [ 3.07962759]]), array([[-0.1690362 ],
       [ 0.02618741],
       [ 3.08879278]]), array([[-0.02682242],
       [ 0.03956976],
       [ 3.09150364]]), array([[-0.0325887 ],
       [ 0.06138676],
       [ 3.11494457]]), array([[-0.02808637],
       [ 0.01986556],
       [ 3.108715  ]]), array([[-0.07009862],
       [ 0.03657897],
       [ 3.07052483]]), array([[-0.0283824 ],
       [ 0.04147083],
       [ 3.09688713]]),

## Right

In [27]:
images = glob.glob('rs/right/*.png')
assert images

objpoints, imgpointsR = plib.FindAllChessCorners(X, Y, images)

In [28]:
print(np.asarray(objpoints).shape)
print(np.asarray(imgpointsR).shape)

(76, 54, 3)
(76, 54, 1, 2)


In [37]:
calRight = cv2.calibrateCamera(objpoints, imgpointsR, (w, h), None, None)

In [38]:
print(calRight)

(0.30681245357051373, array([[375.12051601,   0.        , 321.76648186],
       [  0.        , 375.43832028, 244.06321694],
       [  0.        ,   0.        ,   1.        ]]), array([[-0.0027914 , -0.01328751,  0.00292249,  0.00138688,  0.00552691]]), [array([[ 0.43396635],
       [-0.06482311],
       [ 2.54123895]]), array([[ 0.26102184],
       [-0.07296197],
       [ 2.72172173]]), array([[ 0.04498478],
       [-0.0548633 ],
       [-3.11917831]]), array([[-0.14896178],
       [ 0.00801531],
       [ 3.05819646]]), array([[-0.20351928],
       [ 0.08384838],
       [ 3.08014871]]), array([[-0.1717805 ],
       [ 0.02486315],
       [ 3.08932743]]), array([[-0.02814456],
       [ 0.04008828],
       [ 3.0920107 ]]), array([[-0.03399759],
       [ 0.06279491],
       [ 3.11537047]]), array([[-0.03052558],
       [ 0.02001388],
       [ 3.10941518]]), array([[-0.07143074],
       [ 0.03696948],
       [ 3.0713087 ]]), array([[-0.02724743],
       [ 0.04185535],
       [ 3.09787025]])

In [33]:
r1 = np.zeros(3,3)
t1
F
E

wat = cv2.stereoCalibrate(objpoints, imgpointsL, imgpointsR, (w, h), None, None, None, None)
for elem in wat:
    print(elem)

146.90273469016464
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]]
[[ 9.98460696e-01 -5.54636306e-02 -1.52692718e-04]
 [ 5.54636255e-02  9.98460708e-01 -3.73986672e-05]
 [ 1.54531945e-04  2.88722076e-05  9.99999988e-01]]
[[-0.25272374]
 [-0.22498753]
 [-0.00058847]]
[[-2.12925164e-06  5.81065201e-04 -2.24987545e-01]
 [-5.48507190e-04  3.99352036e-05  2.52723826e-01]
 [ 2.10624227e-01 -2.64813349e-01 -2.49024258e-05]]
[[ 8.55037842e-02 -2.33336786e+01  9.03476420e+03]
 [ 2.20262554e+01 -1.60366720e+00 -1.01485626e+04]
 [-8.45798030e+03  1.06340382e+04  1.00000000e+00]]


# Step 2: rectify